/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.gui;

import javax.swing.*;

/**
 *
 * @author alexander
 */
@SuppressWarnings("serial")
public final class DateInputPanel extends JPanel {

    /**
     * Creates new form DateInputPanel
     */
    public DateInputPanel() {
        initComponents();
    }
    
    public int getDay() {
        final int result = Integer.valueOf(day.getText());
        if (result <= 0 ) throw new NumberFormatException("Invalid day");
        switch (getMonth()) {
            case 1: case 3: case 5: case 7:
            case 8: case 10: case 12:
                if (result > 31) throw new NumberFormatException("Invalid day");
                break;
            case 4: case 6: case 9: case 11:
                if (result > 30) throw new NumberFormatException("Invalid day");
                break;
            case 2:
                if (isLeap(getYear())) {
                    if (result > 29) throw new NumberFormatException("Invalid day"); 
                } else {
                    if (result > 28) throw new NumberFormatException("Invalid day");
                }
        }
        return result;
    }
    
    public int getMonth() {
        final int result = Integer.valueOf(month.getText());
        if (result < 1 || result > 12) {
            throw new NumberFormatException("Invalid month");
        }
        return result;
    }
    
    public int getYear() {
        return Integer.valueOf(year.getText());
    }
    
    public void setDay(int day) {
        this.day.setText(String.valueOf(day));
    }
    
    public void setMonth(int month) {
        this.month.setText(String.valueOf(month));
    }
    
    public void setYear(int year) {
        this.year.setText(String.valueOf(year));
    }
    
    private static boolean isLeap(int year) {
        return (year % 4 == 0) && ((year % 100 != 0) || (year % 400 == 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        day = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        year = new javax.swing.JTextField();

        day.setText("day");
        day.setName("day"); // NOI18N

        month.setText("month");
        month.setName("month"); // NOI18N

        year.setText("year");
        year.setName("year"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(day, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField day;
    private javax.swing.JTextField month;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
